<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>desktop</string>
	</array>
	<key>name</key>
	<string>Desktop</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#comments</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Required on the first line, Gnome.</string>
			<key>match</key>
			<string>(\[Desktop Entry\])</string>
			<key>name</key>
			<string>keyword.control.desktop</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>12</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.desktop</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>storage.type.desktop</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>storage.type.desktop</string>
				</dict>
				<key>7</key>
				<dict>
					<key>name</key>
					<string>string.unquoted.desktop</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Keys, Gnome.</string>
			<key>match</key>
			<string>(((Encoding|Type|Version|NoDisplay|Hidden|OnlyShowIn|NotShowIn|DBusActivatable|TryExec|Exec|Path|Terminal|Actions|MimeType|Categories|StartupNotify|StartupWMClass|URL|X-(\w|-)+))|((Name|GenericName|Comment|Icon|Keywords)(\[(\w)+(@\w+)?\])?))( |\t)*(=)</string>
			<key>name</key>
			<string>keyword.other.desktop</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>comments</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(^[ \t]+)?(?=#)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.whitespace.comment.leading.thrift</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?!\G)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>begin</key>
							<string>#</string>
							<key>beginCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.comment.thrift</string>
								</dict>
							</dict>
							<key>end</key>
							<string>$</string>
							<key>name</key>
							<string>comment.line.number-sign.thrift</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(^[ \t]+)?(?=//)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.whitespace.comment.leading.thrift</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?!\G)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>begin</key>
							<string>//</string>
							<key>beginCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.comment.thrift</string>
								</dict>
							</dict>
							<key>end</key>
							<string>$</string>
							<key>name</key>
							<string>comment.line.double-slash.thrift</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>/\*\*</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.begin.thrift</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\*/</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.end.thrift</string>
						</dict>
					</dict>
					<key>name</key>
					<string>comment.block.documentation.thrift</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>/\*</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.begin.thrift</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\*/</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.end.thrift</string>
						</dict>
					</dict>
					<key>name</key>
					<string>comment.block.thrift</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>text.desktop</string>
	<key>uuid</key>
	<string>9913fda1-955e-41cf-9f68-8d29461cf722</string>
</dict>
</plist>
